function notify(msg)     game.StarterGui:SetCore("SendNotification", {
Title = "crash cmd users lmao";         
Text = msg;         
Duration = 3;     
}) 
end
notify("fucking up the server")
game.Players.LocalPlayer.Chatted:connect(function(msg)
time = string.sub(msg, 9)
 if msg == ":jp" then
local pads = game:GetService("Workspace").Terrain["_Game"].Admin.Pads:GetChildren("Head")
 
for i, pad in pairs(pads) do
pad.PrimaryPart = pad:FindFirstChild("Head")
local pos = pad.PrimaryPart.CFrame
wait(0)
pad.PrimaryPart.CanCollide = false
pad:SetPrimaryPartCFrame(game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame)
wait(0)
pad:SetPrimaryPartCFrame(pos)
pad.PrimaryPart.CanCollide = true
end
end
 
end)

game.Players:Chat(":jp")
game.Players:Chat(":jp")
game.Players:Chat(":jp")
game.Players:Chat(":jp")
game.Players:Chat(":jp")
game.Players:Chat(":jp")
game.Players:Chat(":jp")
game.Players:Chat(":jp")
game.Players:Chat(":jp")
wait(0.05)
game:GetService'Players':Chat(("jail all"))
game:GetService'Players':Chat(("skydive all"))
game:GetService'Players':Chat(("skydive all"))
game:GetService'Players':Chat(("time -"))
game:GetService'Players':Chat(("blind all"))
wait(0.05)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer(" IMAGINE BEING A COOLKID LMAO ","All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer(" YOU SUCK AT CODING.","All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer(" UNLIKE SCV2","All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer(" JUST GET SCV2.","All")
game:GetService'Players':Chat(("h \n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\ LOL IMAGINE ACTUALLY LIKING COOLKID COOLKID CLONES ARE SKIDS AND DONT KNOW HOW TO CODE. UNLIKE SCV2 DEVS IMAO \n\n\n\n\n\n\n"))
game:GetService'Players':Chat(("h \n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\ LOL IMAGINE ACTUALLY LIKING COOLKID COOLKID CLONES ARE SKIDS AND DONT KNOW HOW TO CODE. UNLIKE SCV2 DEVS IMAO \n\n\n\n\n\n\n"))
game:GetService'Players':Chat(("h \n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\ LOL IMAGINE ACTUALLY LIKING COOLKID COOLKID CLONES ARE SKIDS AND DONT KNOW HOW TO CODE. UNLIKE SCV2 DEVS IMAO \n\n\n\n\n\n\n"))
game:GetService'Players':Chat(("h \n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\ LOL IMAGINE ACTUALLY LIKING COOLKID COOLKID CLONES ARE SKIDS AND DONT KNOW HOW TO CODE. UNLIKE SCV2 DEVS IMAO \n\n\n\n\n\n\n"))
game:GetService'Players':Chat(("jail all"))
wait(0.8)
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
wait(1)
function notify(msg)     game.StarterGui:SetCore("SendNotification", {
Title = "crash cmd users lmao";         
Text = msg;         
Duration = 5;     
}) 
end
notify("fucked up the server")