function notify(msg)     game.StarterGui:SetCore("SendNotification", {
Title = "crash cmd users lmao";         
Text = msg;         
Duration = 3;     
}) 
end
notify("fucking up the server")
game.Players.LocalPlayer.Chatted:connect(function(msg)
time = string.sub(msg, 9)
 if msg == ":jp" then
local pads = game:GetService("Workspace").Terrain["_Game"].Admin.Pads:GetChildren("Head")
 
for i, pad in pairs(pads) do
pad.PrimaryPart = pad:FindFirstChild("Head")
local pos = pad.PrimaryPart.CFrame
wait(0)
pad.PrimaryPart.CanCollide = false
pad:SetPrimaryPartCFrame(game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame)
wait(0)
pad:SetPrimaryPartCFrame(pos)
pad.PrimaryPart.CanCollide = true
end
end

end)
game.Players:Chat(":jp")
game.Players:Chat(":jp")
game.Players:Chat(":jp")
game.Players:Chat(":jp")
game.Players:Chat(":jp")
game.Players:Chat(":jp")
game.Players:Chat(":jp")
game.Players:Chat(":jp")
game.Players:Chat(":jp")
wait(0.05)
game:GetService'Players':Chat(("respawn all"))
game:GetService'Players':Chat(("dog all"))
game:GetService'Players':Chat(("dog all"))
game:GetService'Players':Chat(("time -"))
game:GetService'Players':Chat(("skydive all"))
wait(0.8)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("TIRED OF GETTING CRASHED BY SUPERIOR SCRIPTS? JOIN SCV2 TODAY!","All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("dsc.gg / shortcut","All")
game:GetService'Players':Chat(("h h \n\n\n\n\n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\n\n\n\ TIRED OF GETTING CRASHED BY SUPEIOR SCRIPTS? JOIN SHORTCUT V2 TODAY! ds c . gg / shortcut \n\n\n\n\n\n\n\n\n\n\n\ " ))
game:GetService'Players':Chat(("h h \n\n\n\n\n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\n\n\n\ TIRED OF GETTING CRASHED BY SUPEIOR SCRIPTS? JOIN SHORTCUT V2 TODAY! ds c . gg / shortcut \n\n\n\n\n\n\n\n\n\n\n\ " ))
game:GetService'Players':Chat(("h h \n\n\n\n\n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\n\n\n\ TIRED OF GETTING CRASHED BY SUPEIOR SCRIPTS? JOIN SHORTCUT V2 TODAY! ds c . gg / shortcut \n\n\n\n\n\n\n\n\n\n\n\ " ))
game:GetService'Players':Chat(("h h \n\n\n\n\n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\n\n\n\ TIRED OF GETTING CRASHED BY SUPEIOR SCRIPTS? JOIN SHORTCUT V2 TODAY! ds c . gg / shortcut \n\n\n\n\n\n\n\n\n\n\n\ " ))
game:GetService'Players':Chat(("skydive all,all,all"))
game:GetService'Players':Chat(("time -"))
wait(0.8)
game:GetService'Players':Chat(("time -"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
wait(1)
function notify(msg)     game.StarterGui:SetCore("SendNotification", {
Title = "crash cmd users lmao";         
Text = msg;         
Duration = 5;     
}) 
end
notify("fucked up the server")