
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣄⣀⣀⣀⠀⠀⠀","All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⠿⠿⢿⣿⣶⣤","All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("⢠⣾⣷⣶⠀⠀⠀⢰⣿⡟⠁⠀⠀⠀⠈⠙⠛","All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("⠈⠛⠋⠁⠀⠀⠀⢸⣿⡇⠀⠀⠀⠀⠀⠀⠀","All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("⠀⠀⠀⠀⠀⠀⠀⢸⣿⡇⠀⠀⠀⠀⠀⠀⠀","All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("⠀⠀⠀⠀⠀⠀⠀⢸⣿⣇⠀⠀⠀⠀⠀⠀⠀","All")
wait(1)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("⠀⠀⠀⠀⠀⠀⠀⠀⢿⣿⡄⠀⠀⠀⠀⠀⠀","All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⣷⡀⠀⠀⠀⠀⠀","All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⡄⠀⠀⠀⠀","All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("⠀⣠⣄⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⣦⣤⣤⣀","All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("⠀⠙⠛⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠛⠛⠛⠛","All")
