-- Gui to Lua
-- Version: 3.2

-- Instances:
local prefix = ">"

game.Players.LocalPlayer.Chatted:Connect(function(msg)
        if string.sub(msg:lower(), 0, 7) == prefix .. "bek" then
            local player = string.sub(msg:lower(), 6)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            game.Players:Chat("dog "..player)
            wait(0.1)
            game.Players:Chat("rainbowify "..player)
            game.Players:Chat("clone "..player)
            game.Players:Chat("explode "..player)
end
        if string.sub(msg:lower(), 0, 5) == prefix .. "capy" then
            local player = string.sub(msg:lower(), 6)
            game.Players:Chat("h \n\n\n\n\n\n\n \n\n\n\n\n\n\n\n  CAPYBARA MODE ON \n\n\n\n\n\n\n\n")
            game.Players:Chat("disco")
            game.Players:Chat("time -")
            game.Players:Chat("respawn all")
            game.Players:Chat("hat all 7214548011")
            game.Players:Chat("pants all 7231321773")
            game.Players:Chat("shirt all 7215534569")
            game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("Okay, I pull up, hop out at the after party","All")
            game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("You and all your friends, yeah, they love to get nicely ","All")
            game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("Sippin' on that Henn', I know you love that audi ","All")
            game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("1942, I take you back in that 'Rari ","All")
end
       if string.sub(msg:lower(), 0, 7) == prefix .. "techno" then
            local player = string.sub(msg:lower(), 6)
            game.Players:Chat("respawn all")
            game.Players:Chat("char all 1842223904")
            game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("TECHNO > MIA ","All")
            game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("TECHNO > MIA ","All")
            game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("TECHNO > MIA ","All")
        end
    end)

local ScreenGui = Instance.new("ScreenGui")
local Frame = Instance.new("Frame")
local ice = Instance.new("TextButton")
local cra = Instance.new("TextButton")
local perm = Instance.new("TextButton")

--Properties:

ScreenGui.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")
ScreenGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling

Frame.Parent = ScreenGui
Frame.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Frame.Position = UDim2.new(0.0227920227, 0, 0.0967741907, 0)
Frame.Size = UDim2.new(0, 157, 0, 144)
Frame.Selectable = true
Frame.Draggable = true
Frame.Active = true

ice.Name = "ice"
ice.Parent = Frame
ice.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
ice.Position = UDim2.new(0.0362022966, 0, -0.00060865283, 0)
ice.Size = UDim2.new(0, 145, 0, 41)
ice.Font = Enum.Font.GothamBold
ice.Text = "ice dick lol"
ice.TextColor3 = Color3.fromRGB(0, 0, 0)
ice.TextSize = 30.000
ice.MouseButton1Down:connect(function()
    game:GetService'Players':Chat(("invis me"))
    wait(0.5)
	game:GetService'Players':Chat(("tp me me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("tp me me "))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("tp me me "))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("tp me me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("tp me me "))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("tp me me "))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("tp me me "))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("tp me me "))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("tp me me "))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("tp me me "))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("tp me me "))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService("Players"):Chat(("unskydive me"))
	game:GetService("Players"):Chat(("undog me"))
	game:GetService("Players"):Chat(("tp me me"))
	game:GetService("Players"):Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService("Players"):Chat(("unskydive me"))
	game:GetService("Players"):Chat(("undog me"))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("tp me me "))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("tp me me "))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("tp me me "))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("tp me me "))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("tp me me "))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("tp me me "))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("tp me me "))
	game:GetService'Players':Chat(("tp me me "))
	game:GetService'Players':Chat(("freeze me"))
	game:GetService'Players':Chat(("tp me me "))
	game:GetService'Players':Chat(("freeze me"))
end)

cra.Name = "cra"
cra.Parent = Frame
cra.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
cra.Position = UDim2.new(0.0322402194, 0, 0.62948817, 0)
cra.Size = UDim2.new(0, 145, 0, 41)
cra.Font = Enum.Font.GothamBold
cra.Text = "crash"
cra.TextColor3 = Color3.fromRGB(0, 0, 0)
cra.TextSize = 38.000
cra.MouseButton1Down:connect(function()
	function notify(msg)     game.StarterGui:SetCore("SendNotification", {
		Title = "crash cmd users lmao";         
		Text = msg;         
		Duration = 3;     
		}) 
	end
	notify("fucking up the server")
	game.Players.LocalPlayer.Chatted:connect(function(msg)
		time = string.sub(msg, 9)
		if msg == ":jp" then
			local pads = game:GetService("Workspace").Terrain["_Game"].Admin.Pads:GetChildren("Head")

			for i, pad in pairs(pads) do
				pad.PrimaryPart = pad:FindFirstChild("Head")
				local pos = pad.PrimaryPart.CFrame
				wait(0)
				pad.PrimaryPart.CanCollide = false
				pad:SetPrimaryPartCFrame(game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame)
				wait(0)
				pad:SetPrimaryPartCFrame(pos)
				pad.PrimaryPart.CanCollide = true
			end
		end

	end)
	game.Players:Chat(":jp")
	game.Players:Chat(":jp")
	game.Players:Chat(":jp")
	game.Players:Chat(":jp")
	game.Players:Chat(":jp")
	game.Players:Chat(":jp")
	game.Players:Chat(":jp")
	game.Players:Chat(":jp")
	game.Players:Chat(":jp")
	game:GetService'Players':Chat(("time -"))
	wait(0.8)
	game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("dsc.gg / shortcut","All")
	game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer(" IMAGINE USING CMD'.","All")
	game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer(" LIKE COME ON SCV2 IS THE BEST.","All")
	game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer(" USE SCV2 USE SCV2.","All")
	game:GetService'Players':Chat(("h h \n\n\n\n\n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\n\n\n\ TIRED OF GETTING CRASHED BY SUPEIOR SCRIPTS? THIS IS FOR YOU CMD USERS JOIN SHORTCUT V2 TODAY! ds c . gg / shortcut \n\n\n\n\n\n\n\n\n\n\n\ " ))
	game:GetService'Players':Chat(("h h \n\n\n\n\n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\n\n\n\ TIRED OF GETTING CRASHED BY SUPEIOR SCRIPTS? THIS IS FOR YOU CMD USERS JOIN SHORTCUT V2 TODAY! ds c . gg / shortcut \n\n\n\n\n\n\n\n\n\n\n\ " ))
	game:GetService'Players':Chat(("h h \n\n\n\n\n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\n\n\n\ TIRED OF GETTING CRASHED BY SUPEIOR SCRIPTS? THIS IS FOR YOU CMD USERS JOIN SHORTCUT V2 TODAY! ds c . gg / shortcut \n\n\n\n\n\n\n\n\n\n\n\ " ))
	game:GetService'Players':Chat(("h h \n\n\n\n\n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\n\n\n\ \n\n\n\n\n\n\n\n\n\n\n\ TIRED OF GETTING CRASHED BY SUPEIOR SCRIPTS? THIS IS FOR YOU CMD USERS JOIN SHORTCUT V2 TODAY! ds c . gg / shortcut \n\n\n\n\n\n\n\n\n\n\n\ " ))
	game:GetService'Players':Chat(("skydive all,all,all"))
	game:GetService'Players':Chat(("time -"))
	wait(0.8)
	game:GetService'Players':Chat(("time -"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("size all 0.3"))
	game:GetService'Players':Chat(("freeze all"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("size all 10"))
	game:GetService'Players':Chat(("clone all"))
	wait(1)
	function notify(msg)     game.StarterGui:SetCore("SendNotification", {
		Title = "crash cmd users lmao";         
		Text = msg;         
		Duration = 5;     
		}) 
	end
	notify("fucked up the server")
end)

perm.Name = "perm"
perm.Parent = Frame
perm.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
perm.Position = UDim2.new(0.031847164, 0, 0.300619543, 0)
perm.Size = UDim2.new(0, 145, 0, 41)
perm.Font = Enum.Font.GothamBold
perm.Text = "perm"
perm.TextColor3 = Color3.fromRGB(0, 0, 0)
perm.TextSize = 38.000
perm.MouseButton1Down:Connect(function()
	while true do
		_G.perm = not _G.perm
		local lp = game:GetService("Players").LocalPlayer
		local store = workspace.Terrain._Game
		local pads = store.Admin.Pads
		local regen
		pcall(function()
			regen = store.Admin.Regen
		end)
		local pad = pads:FindFirstChild("Touch to get admin")
		if pad == nil then
			pcall(function()
				fireclickdetector(regen.ClickDetector,0)
				wait(0)
				pad = pads:FindFirstChild("Touch to get admin")
			end)
		end
		local pd = pad:Clone()
		pd.Parent = workspace
		pd.Head.CFrame = pad.Head.CFrame
		pad.Head.Transparency = 1
		pad.Changed:Connect(function(c)
			if c == "Name" then
				pd.Name = pad.Name
			end
		end)
		pad.Head.Changed:Connect(function(v)
			if v == "Color" then
				pd.Head.Color = pad.Head.Color
			end
		end)    
		while game.RunService.Heartbeat:Wait() do
			if _G.perm == true then
				pcall(function()
					if pad == nil then
						pcall(function()
							fireclickdetector(regen.ClickDetector,0)
							wait(0)
							pad = pads:FindFirstChild("Touch to get admin")
						end)
					end
					pad.Head.CanCollide = false
					pad.Head.CFrame = lp.Character.Torso.CFrame
					wait()
					pad.Head.CFrame = lp.Character.Head.CFrame
				end)
			end
		end
	end
end)
